### ISSUE TITLE
Create a Queue using Linked List in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#10]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/21-stacks-queues/src/com/inclass/queue/CustomQueueLinkedList.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Queue is a data structure, which uses the concept of First in First out or Last in Last Out
![](https://cdn.programiz.com/sites/tutorial2program/files/queue.png)

## Use Concepts:

- use structure (`struct`) to create a linked list

- use dynamic memory allocation (`malloc()`) to initial a structure (`struct`)

- create a menu using an infinite switch case which implements all the functions
  ``` 
    1. Enqueue        2. Dequeue
    3. Exit 
  ```
 - display the linked list after all operations

## Create functions:

- `enqueue()` - adds new element at the end of the queue
    - takes an input of a new element from the user

- `dequeue()` - removes the element at the front of the queue

- `display()` - prints queue 
    - preview : " 1 -> 2 -> 3 -> 4 -> 5 -> Null"
    - when the queue is empty -> "Null"

**Comment by Ritam135** [comment]
Please assign me this issue

**Comment by driptanil** [comment]
Start working on it. Have Fun 😁

**Comment by kartikjoshi267** [comment]
I would like to work on this issue.
