### ISSUE TITLE
Create Circular Queue using Array in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#11]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/21-stacks-queues/src/com/inclass/queue/circular/CustomCircularQueueArray.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Circular Queue is a special version of a queue where the last element of the queue is connected to the first element of the queue forming a circle. The operations are performed based on FIFO (First In First Out) principle. It is also called 'Ring Buffer'.
![](https://media.geeksforgeeks.org/wp-content/uploads/Circular-queue_1.png)

- E.g. 
   - [1, 2, 3, 4, 5]   ... ______________________ ... dequeue() x 2
   - [null, null, 3, 4, 5]  ... _________________ ...  enqueue(6)
   - [6, null, 3, 4, 5]

## Use Concepts:

- use dynamic memory allocation (`malloc()`) to declare the array

- use a macro (`# define`) to define the size of the array

- create a menu using an infinite switch case which implements all the functions
  ``` 
    1. Enqueue        2. Dequeue
    3. Exit 
  ```
 - display the array after all operations

## Create functions:

- `enqueue()` - adds new element to the queue
    - when the queue becomes full -> " Full Queue !!!"
    - takes an input of a new element from the user

- `dequeue()` - removes the element at the front of the queue
    - when the queue becomes empty -> " Empty Queue !!!"

- `display()` - prints queue 
    - preview : "[ 1, 2, 3, 4, 5 ]"
    - when the queue is empty -> "Null"

**Comment by Tejas20-03** [comment]
It will be my pleasure to contribute on above issue.

**Comment by driptanil** [comment]
Good Luck!
