### ISSUE TITLE
Create Singly Linked List in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#13]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/20-linked-list/src/com/inclass/SinglyLinkedList.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Linked List is a linear data structure that includes a series of connected nodes. Here, each node stores the data and the address of the next node.
![](https://cdn.programiz.com/sites/tutorial2program/files/linked-list-concept.png)

## Use Concepts:

- use structure (`struct`) to create a linked list
```
typedef struct node {
    int val;
    struct node * next;
}node;
```

- use dynamic memory allocation (`malloc()`) to initial a linked list node (`struct`)

- create a menu using an infinite switch case which implements all the functions
  ``` 
    1. InsertFirst         2. InsertLast
    3. DeleteFirst        4.  DeleteLast         5. Exit
  ```
 - display the linked list after all operations

## Create functions:

- `init()` 
    - takes an integer parameter 
    - declares a node and assigns the integer
    - returns the node

- `insertFirst()` - adds a new node at the front of the linked list
    - takes an input of a new element from the user

- `insertFirst()` - adds a new node at the end of the linked list
    - takes an input of a new element from the user

- `deleteFirst()` 
    - prints the integer at the First node
    - delete the node

- `deleteLast()` 
    - prints the integer at the Last node
    - delete the node

- `display()` - prints stack 
    - preview : "5 -> 4 -> 3 -> 2 -> 1 -> null"
    - when the stack is empty -> "Null"

**Comment by akshitsangwan** [comment]
Hey @driptanil, I'm interested to contribute to this issue. Can you please assign me this task?

**Comment by driptanil** [comment]
Have Fun 😁,

**Comment by driptanil** [comment]
@akshitsangwan Please read the question carefully, and make the change accordingly

**Comment by akshitsangwan** [comment]
Hey @driptanil, I have already raised a PR, you can review and merge my PR accordingly. Glad to contribute:)

**Comment by driptanil** [comment]
@akshitsangwan Follow the instructions

**Comment by Rajanvik** [comment]
Please assign me this issue, i can do this
