### ISSUE TITLE
Create Doubly Linked List in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#16]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/20-linked-list/src/com/inclass/DoublyLinkedList.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Linked List is a linear data structure that includes a series of connected nodes. Here, each node stores the data and the address of the next node.
![](https://cdn.programiz.com/sites/tutorial2program/files/doubly-linked-list-concept.png)

## Use Concepts:

- use structure (`struct`) to create a linked list
```
typedef struct node {
    int val;
    struct node * prev;
    struct node * next;
}node;
```

- use dynamic memory allocation (`malloc()`) to initial a linked list node (`struct`)

- create a menu using an infinite switch case which implements all the functions
  ``` 
    1. InsertFirst         2. InsertLast
    3. DeleteFirst        4.  DeleteLast         5. Exit
  ```
 - display the linked list after all operations

## Create functions:

- `init()` 
    - takes an integer parameter 
    - declares a node and assigns the integer
    - returns the node

- `insertFirst()` - adds a new node at the front of the linked list
    - takes an input of a new element from the user

- `insertFirst()` - adds a new node at the end of the linked list
    - takes an input of a new element from the user

- `deleteFirst()` 
    - when linked list is empty -> print "`Empty Linked List !!!`"
    - prints the integer at the First node
    - delete the node

- `deleteLast()` 
    - when linked list is empty -> print "`Empty Linked List !!!`"
    - prints the integer at the Last node
    - delete the node

- `display()` - prints stack 
    - preview : "`null <- 5 <-> 4 <-> 3 <-> 2 <-> 1 -> null`"
    - when the stack is empty -> "`null`"

**Comment by Adiii1436** [comment]
Hello! I want to work on this issue.

**Comment by patil-prathamesh** [comment]
I want to work on this issue

**Comment by driptanil** [comment]
Sure, Read the instructions carefully, and code accordingly 

Comment below if you have understood the instructions, 

Then I will assign you, this issue @Adiii1436

**Comment by Adiii1436** [comment]
Yes I understood the instructions. I can code it in C.

**Comment by driptanil** [comment]
@Adiii1436 Good Luck

**Comment by hemantwasthere** [comment]
Hey @driptanil, can i work on this issue too
