### ISSUE TITLE
Create Circular Linked List in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#17]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/20-linked-list/src/com/inclass/CircularLinkedList.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Circular Linked List is a Singly Linked List, where the last node points to the first node
![](https://cdn.programiz.com/sites/tutorial2program/files/circular-linked-list.png)

## Use Concepts:

- use structure (`struct`) to create a linked list
```
typedef struct node {
    int val;
    struct node * next;
}node;
```

- use dynamic memory allocation (`malloc()`) to initial a linked list node (`struct`)

- create a menu using an infinite switch case which implements all the functions
  ``` 
    1. InsertFirst         2. InsertLast
    3. DeleteFirst        4.  DeleteLast         5. Exit
  ```
 - display the linked list after all operations

## Create functions:

- `init()` 
    - takes an integer parameter 
    - declares a node and assigns the integer
    - returns the node

- `insertFirst()` - adds a new node at the front of the linked list
    - takes an input of a new element from the user

- `insertFirst()` - adds a new node at the end of the linked list
    - takes an input of a new element from the user

- `deleteFirst()` 
    - when the linked list is empty -> print "`Empty Linked List !!!`"
    - prints the integer at the First node
    - delete the node

- `deleteLast()` 
    - when the linked list is empty -> print "`Empty Linked List !!!`"
    - prints the integer at the Last node
    - delete the node

- `display()` - prints stack 
    - preview : "`-->> 5 -> 4 -> 3 -> 2 -> 1 -->>`"
    - when the stack is empty -> "`null`"

**Comment by surazkarn** [comment]
May you please assign me this ? I am happy to contribute.

**Comment by driptanil** [comment]
Sure, Read the instructions carefully, and code accordingly

Comment below if you have understood the instructions,

Then I will assign you, this issue @surazkarn

**Comment by surazkarn** [comment]
Yes I have understood the instructions , I will code it in C .

**Comment by patil-prathamesh** [comment]
I am good at DSA. I can do this as instructions.

**Comment by hemantwasthere** [comment]
Hello @driptanil, Can you make me assignee also

**Comment by driptanil** [comment]
@hemantwasthere No copy pasting code

**Comment by Ritam135** [comment]
Please assign me this issue

**Comment by driptanil** [comment]
@Ritam135 Good Luck !!!

**Comment by Sscuber03** [comment]
May i be assigned this issue, i have understood the assignment, and i am ready to contribute.
