### ISSUE TITLE
Create Quick Sort Algorithm in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#20]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/17-quick-sort/QuickSort.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Quick Sort Algorithm
   - Pivot: Any Reference Variable
   - After the first pass:
   - all the elements < pivot will be on the left side
   - all the elements > pivot will be on the right side

## Create functions:

- `lastPivotSort()` : where pivot is end element

   1. (5, 3, 2, 1, 6)
   2. (5, 3, 2, 1) + (6)
   3. (1, 2, 3, 5) + (6)
   4. (1, 2, 3) + (5) + (6)
   5. (1, 2) + (3) + (5) + (6)
   6. (1) + (2) + (3) + (5) + (6)
   7. (1, 2, 3, 5, 6)

- `firstPivotSort()`: where pivot is front element

    1. (5, 3, 2, 1, 6)
    2. (1, 2, 3, 5) + (6)
    3. (1) + (2, 3, 5) + (6)
    4. (1) + (2) + (3, 5) + (6)
    5. (1) + (2) + (3) + (5) + (6)
    6. (1, 2, 3, 5, 6)

- `middlePivotSort()`: where pivot is mid element

  1. (2, 3, 5, 1, 6)
  2. (1) + (2, 3, 5, 6)
  3. (1) + (2, 3) + (5, 6)
  4. (1) + (2) + (3) + (5) + (6)
  5. (1, 2, 3, 5, 6)

- `display()` : prints array
   - "`[ 1, 2, 3, 4, 5 ]`"

**Comment by Tejas20-03** [comment]
It will be my pleasure to contribute to this issue.

**Comment by hemantwasthere** [comment]
Hey @driptanil, I would like to work on this issue

**Comment by driptanil** [comment]
Sure, Read the instructions carefully, and code accordingly

Comment below if you have understood the instructions,

Then I will assign you, this issue @hemantwasthere @Tejas20-03

**Comment by hemantwasthere** [comment]
Yeah sure

**Comment by nitesh-147** [comment]
I have understood the instructions and I can code accordingly it in C. I will be happy if you assign me this.

**Comment by IayushCoderJOD** [comment]
please assign this issue to me I had read instructions very well @driptanil

**Comment by driptanil** [comment]
No worries @IayushCoderJOD I am creating more issue, stay tuned
