### ISSUE TITLE
Create a Binary Tree in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#28]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/22-binary-tree/src/CustomBinaryTree.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Binary Tree is a non-linear data structure in which each parent node can have at most two children.
![](https://cdn.emre.me/2019-07-26-binary-tree.png)

## Use Concepts:

- use structure (`struct`) to create a linked list
typedef struct node {
    int val;
    struct node * left;
    struct node * right;
}tree;

- use dynamic memory allocation (`malloc()`) to initial a linked list node (`struct`)

- create a menu using an infinite switch case which implements all the functions
   
    1. Create using Array          2. PreOrder Traverse
    3. InOrder Traverse            4. PostOrder Traverse         5. Exit
  
 - display the linked list after all operations

## Create functions:

- `init()` 
    - takes an integer parameter 
    - declares a node and assigns the integer
    - returns the node

- `arrayToTree(int [] arr)`
    - takes an array of the binary trees from the user

- `preOrderTraversal()` 
   - recurively print MID, LEFT, RIGHT
   - <img src="https://wat-images.s3.ap-south-1.amazonaws.com/images/ps/preorder-traversal.svg" width="300"/>

- `inOrderTraversal()` 
   - recurively print LEFT, MID, RIGHT
   - <img src="https://wat-images.s3.ap-south-1.amazonaws.com/images/ps/inorder-traversal.svg" width="300"/>

- `postOrderTraversal()` 
   - recurively print LEFT, RIGHT, MID
   - <img src="https://wat-images.s3.ap-south-1.amazonaws.com/images/ps/postorder-traversal.svg" width="300"/>

**Comment by Sscuber03** [comment]
Can this issue be assigned to me? I would love to solve this issue, and also learn more about tree by solving this, and clear my concepts

**Comment by AyushAgrawal25** [comment]
Hi I want to contribute,

Can this issue be assigned to me?

**Comment by SubiditaB** [comment]
please assign me this issue
