### ISSUE TITLE
Bubble Sort in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#32]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/08-bubble-sort/src/com/inclass/BubbleSort.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)
 
## Fundamentals

Bubble Sort is also called Sinking or Exchange Sort.

In every step, adjacent elements are compared and swapped.

![](./image1.png)

-   Space Complexity = $O(1)$ [In-place Sorting Algorithm]
    
-   Time Complexity :
    
    -   Best Case : $O(n)$
    -   Worst Case : $O(n^2)$
    
-   In-place Sorting:
    -   A Sorting Algorithm which uses constant Space Complexity i.e. zero Auxiliary Space
-   Stable Sorting:
    -   A Sorting Algorithm without changing indexes of equal elements while sorting.

**Comment by PALSAMIRAN** [comment]
assign me this issue

**Comment by yash-sharma13** [comment]
assign this to me please

**Comment by vilasrhegde** [comment]
Hey @driptanil  i have pulled the request and can you merge it and have a look at it. Thanks
