### ISSUE TITLE
Selection Sort in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#35]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/09-selection-sort/src/com/inclass/SelectionSort.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)
 
## Fundamentals

-   In-place Sorting:
    -   A Sorting Algorithm which uses constant Space Complexity i.e. zero Auxiliary Space
-   Stable Sorting:
    -   A Sorting Algorithm without changing indexes of identical elements while sorting.

In Selection Sort, the Largest or Smallest element is selected and placed in the correct place.

-   Time Complexity :
    -   Best Case: $O(n^2)$
    -   Worst Case: $O(n^2)$
-   Space Complexity : $O(1)$ [In-place Sorting]
-   Non-Stable Sorting Algorithm
-   Use Case: Performs well in small arrays

## Function

- `minselectionSort()`: finding the minimum element and placing it in the minimum index
- `maxselectionSort()`: finding the maximum element and placing it in the maximum index

**Comment by PALSAMIRAN** [comment]
Assign this issue. I will do it.

**Comment by driptanil** [comment]
Ok
