### ISSUE TITLE
Binary Search in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#38]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/07-binary-search/src/com/inclass/BinarySearch.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)
 
### Time Complexity :

-   Best Case: $O ( 1 )$
-   Worst Case : $O ( log (n) )$ [ where n is number of element in the array ]

### Steps for Binary Search :

1.  Find the middle element.
2.  Compare the target element with the middle element :
    1.  if target element > middle element :
        1.  if Ascending Array: search on the left side of the array.
        2.  if Descending Array: search on the right side of the array.
    2.  if target element < middle element :
        1.  if Ascending Array: search on the right side of the array.
        2.  if Descending Array: search on the left side of the array.
    3.  if target element = middle element :
        1.  return the element

**Comment by SOHAMmondal2003** [comment]
assigned me this issue

**Comment by real-zit** [comment]
Please assign me this issue
