### ISSUE TITLE
Linear Search in C 

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#39]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/06-linear-search/src/com/inclass/LinearSearch.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)
 
## Fundamentals

Time Complexity :

-   Best Case: $O ( 1 )$
    
-   Worst Case: $O ( n )$ [ where n is the size of the array ]

Algorithm:

Traverse all elements in the array, and check for the target element

**Comment by SOHAMmondal2003** [comment]
Assigned me this issue

**Comment by imdebamrita** [comment]
I can also do this well...please assigned me this
