### ISSUE TITLE
Insertion Sort in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#42]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/10-insertion-sort/InsertionSort.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)
 
## Fundamentals

Insertion sort is a simple sorting algorithm that works similar to the way you sort playing cards in your hands. The array is virtually split into a sorted and an unsorted part. Values from the unsorted part are picked and placed at the correct position in the sorted part

-   Space Complexity : $O(1)$ [In-place Sorting Algorithm]
-   Time Complexity :
    -   Best Case : $O(n)$
    -   Worst Case: $O(n^2)$
-   Stable Sorting Algorithm
-   Use Case: When the array is partially sorted.

**Comment by Panchojanyya** [comment]
Assign me this issue

**Comment by acash1809** [comment]
@driptanil please assign this to me as well

**Comment by ShubhamShakyawal** [comment]
@driptanil Assign me please
