### ISSUE TITLE
Merge Sort in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#44]
## Rules:

- Modify the file https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/16-merge-sort/MergeSort.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals

Steps:

1. Divide Array into 2 parts
2. Sort both parts via Recursion
3. Merge the sorted parts
- Dividing Arrays:
    1. {5, 3, 2, 1, 4}
    2. {5, 3} + {2, 1, 4}
    3. {5} + {3} + {2} + {1, 4}
    4. {5} + {3} + {2} + {1} + {4}
- Merging Arrays:
    1. {5} + {3} + {2} + {1} + {4}
    2. {5} + {3} + {2} + {1, 4}
    3. {3, 5} + {1, 2, 4}
    4. {1, 2, 3, 4, 5}

**Comment by Panchojanyya** [comment]
please assign me this issue

**Comment by driptanil** [comment]
Good Luck @Panchojanyya
