### ISSUE TITLE
Custom Queue using Array in C

### ISSUE THREAD

**Issue by driptanil** [driptanil/DSA-Data-Structures-Algorithms#9]
## Rules:

- Modify the https://github.com/driptanil/DSA-Data-Structures-Algorithms/blob/main/21-stacks-queues/src/com/inclass/queue/CustomQueueArray.c

- WARNING !!! : Don't copy and paste code from the internet

- Comment below if you want to be assigned to this issue (then start working on the issue)

## Fundamentals:

- Queue is a data structure, which uses the concept of First in First out or Last in Last Out
![](https://cdn.programiz.com/sites/tutorial2program/files/queue.png)

## Use Concepts:

- use dynamic memory allocation (`malloc()`) to declare the array

- use a macro (`# define`) to define the size of the array

- create a menu using an infinite switch case which implements all the functions
  ``` 
    1. Enqueue        2. Dequeue
    3. Exit 
  ```
 - display the array after all operations

## Create functions:

- `enqueue()` - adds new element at the end of the queue
    - when the queue becomes full -> " Full Queue !!!"
    - takes an input of a new element from the user

- `dequeue()` - removes the element at the front of the queue
    - when the queue becomes empty -> " Empty Queue !!!"

- `display()` - prints queue 
    - preview : "[ 1, 2, 3, 4, 5 ]"
    - when the queue is empty -> "Null"

**Comment by Tejas20-03** [comment]
It will be my pleasure to contribute on above issue.

**Comment by driptanil** [comment]
@Tejas20-03 Take your time with issue assigned to you

**Comment by island-coder** [comment]
Is it possible to work on this?

**Comment by driptanil** [comment]
Sure, Read the instructions carefully, and code accordingly

Comment below if you have understood the instructions,

Then I will assign you, this issue @island-coder

**Comment by island-coder** [comment]
Sure

**Comment by patil-prathamesh** [comment]
I can do this very well.

**Comment by driptanil** [comment]
@patil-prathamesh I have already assigned you an issue, first create a pull request
